---
title: "Time Series"
format:
  html:
    embed-resources: true
---

Even though in theory the LSTM networks are able to work with the time dependencies (tendency and seasonality) works like [Time series forecasting - with deep learning](https://rpubs.com/zkajdan/279967) and [How to use timesteps in LSTM networks for time series forecasting](https://machinelearningmastery.com/use-timesteps-lstm-networks-time-series-forecasting/) suggest to transform the time series. In this app the user has the option to use the original time series and the following transformation:

1.  First transformation: This transformation parts from the basic idea that the time series used most be stationary. With that in mind, if the original time series is not stationary will be differentiated in the necessary order to meet that requirement.
2.  Second transformation: Equal to the first transformation, the time series to work with most be stationary. Different to the first transformation, before apply the difference to the time series a logarithmic transformation will be applied.

::: {.callout-note}
By default, the exact values of the series and those resulting from scaling them in the following ranges will be taken into account: from 0 to 1; from -1 to 1. The user can decide whether to continue with the default options or use only the ones they want.
:::

The goal of using multiple time series is to know how much the obtained results of the models vary in dependency of the selected time series to build the training vectors.
